enum ENUM_MediaType {
  UNKNOW = "null",
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
}

interface MovieScreenDataType {
  cnContent?: string;
  enContent?: string;
  hasMedia: boolean;
  timer: number;
  mediaType: ENUM_MediaType;
  mediaUrl?: string;
  isEnd: boolean;
  musicText1?: string;
  musicText2?: string;
  speakText1?: string;
  speakText2?: string;
  mediaHorizontal?: boolean;
  rotate?: number;
  startBgMusic?: boolean;
}

const movieData: MovieScreenDataType[] = [
  {
    cnContent: "人的一生有三万多天...",
    enContent: "There are more than 30,000 days in a person's life",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "很开心这一天您专程为我们而来",
    enContent: "I'm so glad you could make this day just for us",
    hasMedia: false,
    timer: 5,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "- 我们订婚啦 -",
    enContent: "Our Betrothal",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "杨璇 & 成怡",
    enContent: "CYXI",
    hasMedia: false,
    timer: 5,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "我们的开始. . .",
    enContent: "The Dawn of Our Love...",
    hasMedia: false,
    timer: 2,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },

  {
    hasMedia: true,
    timer: 7,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen1.webp",
    isEnd: false,
    musicText1: "我为你翻山越岭",
    musicText2: "却无心看风景",
    speakText1: "我们的开始",
    speakText2: "鼓足勇气",
    mediaHorizontal: false,
    rotate: -2,
    startBgMusic: true,
  },
  {
    hasMedia: true,
    timer: 9,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen2.webp",
    isEnd: false,
    musicText1: "我想你，鼓足勇气",
    musicText2: "凭爱的地图散播讯息",
    speakText1: "我爱你bbb",
    speakText2: "我爱你bbb",
    mediaHorizontal: false,
    rotate: -6,
  },
  {
    hasMedia: true,
    timer: 7,
    mediaType: ENUM_MediaType.IMAGE,
    //改成一张有爱的图片
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen3.webp",
    isEnd: false,
    musicText1: "我永远保护你",
    musicText2: "爱就一个字",
    speakText1: "我爱你bbb",
    speakText2: "我爱你bbb",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen4.webp",
    isEnd: false,
    musicText1: "♪ ♩ ∮ ¶ ♬",
    musicText2: "♩ ♫ ♬ ¶ ‖ ♭ ♬ ¶",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen5.webp",
    isEnd: false,
    musicText1: "♪ ♩ ∮ ¶ ♬",
    musicText2: "¶ ♩ ♫ ♬ ‖ ♭ ♬ ¶",
    speakText1: "我爱你333",
    speakText2: "我爱你333",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 11,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen6.webp",
    isEnd: false,
    musicText1: "拨开天空的乌云",
    musicText2: "像蓝丝绒一样美丽",
    speakText1: "我爱你333",
    speakText2: "我爱你333",
    mediaHorizontal: false,
    rotate: 3,
  },
  // 演唱会
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen8.webp",
    isEnd: false,
    musicText1: "我想你，身不由己",
    musicText2: "每个念头有新的梦境",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  // 送礼物
  {
    hasMedia: true,
    timer: 9,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen10.webp",
    isEnd: false,
    musicText1: "但愿你没忘记",
    musicText2: "我永远保护你",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen9.webp",
    isEnd: false,
    musicText1: "两个人相互辉映",
    musicText2: "光芒胜过夜晚繁星",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: 5,
  },
  {
    hasMedia: true,
    timer: 5,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen9.webp",
    isEnd: false,
    musicText1: "我为你翻山越岭",
    musicText2: "却无心看风景",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: 5,
  },
  {
    hasMedia: true,
    timer: 9,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen9.webp",
    isEnd: false,
    musicText1: "我想你，鼓足勇气",
    musicText2: "凭爱的地图散播讯息",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: 5,
  },

  {
    hasMedia: true,
    timer: 5,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen9.webp",
    isEnd: false,
    musicText1: "我永远保护你",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: 5,
  },

  {
    hasMedia: true,
    timer: 7,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen11.webp",
    isEnd: false,
    musicText1: "爱就一个字，我只说一次",
    musicText2: "你知道我只会用行动表示",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -2,
  },
  {
    hasMedia: true,
    timer: 4,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen12.webp",
    isEnd: false,
    musicText1: "守住了坚持",
    musicText2: "看我为你孤注一掷",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 7,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen12.webp",
    isEnd: false,
    musicText1: "爱就一个字，我只说一次",
    musicText2: "恐怕听见的人勾起了相思",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen13.webp",
    isEnd: false,
    musicText1: "搜索你的影子",
    musicText2: "让你幸福我愿意试",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -2,
  },

  // 间奏三张
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen4.webp",
    isEnd: false,
    musicText1: "♪ ♩ ∮ ¶ ♬",
    musicText2: "♩ ♫ ♬ ¶ ‖ ♭ ♬ ¶",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen4.webp",
    isEnd: false,
    musicText1: "♪ ♩ ∮ ¶ ♬",
    musicText2: "♩ ♫ ♬ ¶ ‖ ♭ ♬ ¶",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen4.webp",
    isEnd: false,
    musicText1: "♪ ♩ ∮ ¶ ♬",
    musicText2: "♩ ♫ ♬ ¶ ‖ ♭ ♬ ¶",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },

  {
    hasMedia: true,
    timer: 6,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText1: "我想你，鼓足勇气",
    musicText2: "凭爱的地图散播讯息",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 11,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText1: "但愿你  没忘记",
    musicText2: "我永远保护你",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 7,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText1: "你知道我只会用行动表示",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 11,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText1: "看我为你孤注一掷",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 4,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText1: "承诺一辈子",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 7,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText1: "付出永远不会太迟",
    speakText1: "我爱你222",
    speakText2: "我爱你222",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 16,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen15.webp",
    isEnd: false,
    musicText1: "任时光飞逝，搜索你的影子",
    musicText2: "让你幸福是我一生在乎的事",
    speakText1: "我爱你",
    speakText2: "我爱你 ♡ ♡ ♡",
    mediaHorizontal: true,
    rotate: 6,
  },
  {
    cnContent: "未完待续...",
    enContent: "Our love will endure for all time.",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: true,
  },
];

export { movieData, MovieScreenDataType, ENUM_MediaType };
