enum ENUM_MediaType {
  UNKNOW = "null",
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
}

interface MovieScreenDataType {
  cnContent?: string;
  enContent?: string;
  hasMedia: boolean;
  timer: number;
  mediaType: ENUM_MediaType;
  mediaUrl?: string;
  isEnd: boolean;
  musicText?: string;
  speakText?: string;
  mediaHorizontal?: boolean;
  rotate?: number;
}

const movieData: MovieScreenDataType[] = [
  {
    cnContent: "人的一生有三万多天...",
    enContent: "There are more than 30,000 days in a person's life",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "很开心这一天您专程为我们而来",
    enContent: "I'm so glad you could make this day just for us",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "- 我们订婚啦 -",
    enContent: "Our Betrothal",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },
  {
    cnContent: "杨璇 & 成怡",
    enContent: "CYXI",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: false,
  },

  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen1.webp",
    isEnd: false,
    musicText: "爱就一个字aaa",
    speakText: "我爱你aaa",
    mediaHorizontal: false,
    rotate: -2,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen2.webp",
    isEnd: false,
    musicText: "爱就一个字bbb",
    speakText: "我爱你bbb",
    mediaHorizontal: false,
    rotate: -6,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen3.webp",
    isEnd: false,
    musicText: "爱就一个字111",
    speakText: "我爱你111",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen4.webp",
    isEnd: false,
    musicText: "爱就一个字222",
    speakText: "我爱你222",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen5.webp",
    isEnd: false,
    musicText: "爱就一个字333",
    speakText: "我爱你333",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen6.webp",
    isEnd: false,
    musicText: "爱就一个字555",
    speakText: "我爱你555",
    mediaHorizontal: false,
    rotate: 3,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen7.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: true,
    rotate: -6,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen8.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen9.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
    rotate: 5,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen10.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen11.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
    rotate: -2,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen12.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
    rotate: -8,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen13.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
    rotate: -2,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen14.webp",
    isEnd: false,
    musicText: "爱就一个字",
    speakText: "我爱你",
    mediaHorizontal: false,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen15.webp",
    isEnd: false,
    musicText: "爱就一个字1a1a",
    speakText: "我爱你1a1a",
    mediaHorizontal: true,
    rotate: 6,
  },
  {
    hasMedia: true,
    timer: 3,
    mediaType: ENUM_MediaType.IMAGE,
    mediaUrl: "https://www.onelight.ink/assets/movieScreen/movieScreen16.webp",
    isEnd: false,
    musicText: "爱就一个字1b1b",
    speakText: "我爱你1b1b",
    mediaHorizontal: true,
  },
  {
    cnContent: "结束，开始吃饭",
    enContent: "eat eat eat",
    hasMedia: false,
    timer: 3,
    mediaType: ENUM_MediaType.UNKNOW,
    isEnd: true,
  },
];

export { movieData, MovieScreenDataType, ENUM_MediaType };
